# last change 2014-11-26

html: index.html

index.html: *.txt *.css .lispwords
	txt2page index.txt intro.txt erllib.txt lazystudent.txt \
	craps.txt elevators.txt umbrella.txt distrib.txt bibliog.txt

clean:
	rm -fr *.html
